### ISSUE TITLE
Directly use COCOS information from data dictionary

### ISSUE THREAD

**Issue by orso82** [gafusion/omas#103]
Now IMAS DD includes COCOS information. We need to decipher their nomenclature and interface it with what we already have in OMAS.

https://github.com/gafusion/omas/commit/fc7fc3d819958a4ef54e40f91117fd570ab2a35a#diff-63fbd44b1acff31692fb109a7e658549

**Comment by bclyons12** [comment]
@orso82 Do you have a link to the documentation of the change?

**Comment by orso82** [comment]
This is the relevant issue on the ITER JIRA tracker: https://jira.iter.org/browse/IMAS-1464
