### ISSUE TITLE
add core_sources sample

### ISSUE THREAD

**Issue by orso82** [gafusion/omas#106]

**Comment by TimSlendebroek** [comment]
see https://github.com/gafusion/omas/pull/104/commits/3cb99f222eaad7214e0f601609c0092c414cdd8e

**Comment by orso82** [comment]
In general looks good. The please note that the sample files should be small! with few radial locations. Can you please generate a sub-sampled ODS for this? You can follow this example to do it easily: https://gafusion.github.io/omas/auto_examples/omas_resample.html#sphx-glr-auto-examples-omas-resample-py
