### ISSUE TITLE
No access to repository

### ISSUE THREAD

**Issue by bclyons12** [gafusion/omas#15]
@orso82 I worked on the COCOS functionality for core_profiles and core_sources.  While I was able to clone the repository, I can't push to remote.  I'd like to make a remote development branch and pull request my changes.  Could you add me please?

**Comment by smithsp** [comment]
From the team settings, this appears to be resolved.  For other repos, @bclyons12 should know that he can always fork the repo, and then still have access to pushing and pull requests from the fork.
