### ISSUE TITLE
IMAS 3.34.0 breaks gas_injection IDS

### ISSUE THREAD

**Issue by orso82** [gafusion/omas#173]
@eldond IMAS just released version 3.34.0 of the data dictionary.
The new release changes how gas_injection IDS is structured, specifically, it looks like `valve` is not under `pipe` anymore.

See the new arrangement:
![image](https://user-images.githubusercontent.com/1537880/138170952-c2607db0-cdce-4dc8-93d3-930edcea235f.png)

You can do `make test_no_munittest` in the top-level `omas` directory to see the failing test

**Comment by eldond** [comment]
Oh dear. I suppose I have to test for IMAS schema version and do two versions of things that look this stuff up, right?

**Comment by orso82** [comment]
@eldond I need to release a new version of OMAS soon, definitely by the end of this week, so I have made the minimal fix to make the gas_injection regression work. Still, it would be great if you could bring both the sample as well as the plotting routines up to speed with the new IDS organization.

**Comment by eldond** [comment]
@orso82 I'm starting on it.
