### ISSUE TITLE
Incorrect path in `wall_overlay`

### ISSUE THREAD

**Issue by kripnerl** [gafusion/omas#206]
The vessel plotting uses probably some older version of IMAS: 

https://github.com/gafusion/omas/blob/master/omas/omas_plot.py#L2483-L2484

Schema: https://gafusion.github.io/omas/schema/schema_wall.html
uses either `annular` or `element` to describe the wall.

**Comment by orso82** [comment]
Thank you for reporting @kripnerl !
May I ask how did you happen to find out? This may be useful to track down other places where we are not doing this right.
Also, do you know starting what IMAS version there was this change?

@jmcclena could you please take a look at this?
How does that affect the machine mappings, and the `OMFITgeqdsk.to_omas()` functions?

I am surprised we have not caught this error before...

**Comment by jmcclena** [comment]
@orso82 `OMFITgeqdsk.to_omas()` is fine, as efit has information on the limiter, not the vessel. As far back as 3_10_0, the wall vessel always used annular or element to describe it.   As this plotting was probably written to plot the limiter, I suspect that when writing this function, it was assumed that the limiter and vessel have path structure, when they do not.

**Comment by kripnerl** [comment]
@orso82 I created attempt here on C-U to implement whole COMPASS-U in IMAS data-structure (for the convenience of using OMAS :-)) and to have single "source of true". Therefore, we are creating the structure "by hand" from the engineering drawing. 

I am afraid, the only way how to test this is to create test tokamak with filled all fields and let it pass IMAS version consistency check. 

If I have some time today or tomorrow I will try to write patch for this.

**Comment by orso82** [comment]
@kripnerl it's great to hear about COMPASS-U in IMAS. If you could provide a patch that would be great!

**Comment by kripnerl** [comment]
@orso82 
Suggested MR: #207 

I would not call it C-U in IMAS :-) But using IMAS structure to describe data. No IMAS database involved.
