### ISSUE TITLE
Loading  pressure from Thompson scattering and CHERS on NSTX

### ISSUE THREAD

**Issue by odstrcilt** [gafusion/omas#208]
Is it possible to load pressure from TS and CHERS on NSTX? I have check the file /omas/machine_mappings/nstxu.py and it is all about magnetics

**Comment by smithsp** [comment]
No Thomson or CHERS seen in https://github.com/gafusion/omas/blob/master/omas/machine_mappings/nstxu.py .

**Comment by smithsp** [comment]
Fetching scripts for Thomson already exist in EFITtime and OMFITprofiles in OMFIT.  @odstrcilt and @avdeevag to post links to them here.  @jmcclena to try to port.

**Comment by odstrcilt** [comment]
@jmcclena  here is what needs to be loaded for Te and ne from MDS+ on NSTX

```

        TS_MDS = '\\ACTIVESPEC::TOP.MPTS.OUTPUT_DATA.BEST.'
        ne = OMFITmdsValue(server='NSTX', treename='ACTIVESPEC', shot=shot, TDI=TS_MDS + 'FIT_NE').data()
        ne_err = OMFITmdsValue(server='NSTX', treename='ACTIVESPEC', shot=shot, TDI=TS_MDS + 'FIT_NE_ERR').data()
        te = OMFITmdsValue(server='NSTX', treename='ACTIVESPEC', shot=shot, TDI=TS_MDS + 'FIT_TE').data() * 1e3  # eV
        te_err = OMFITmdsValue(server='NSTX', treename='ACTIVESPEC', shot=shot, TDI=TS_MDS + 'FIT_TE_ERR').data() * 1e3  # eV
        R = OMFITmdsValue(server='NSTX', treename='ACTIVESPEC', shot=shot, TDI=TS_MDS + 'FIT_RADII').data() * 1e-2  # m
        time = OMFITmdsValue(server='NSTX', treename='ACTIVESPEC', shot=shot, TDI=TS_MDS + 'TS_TIMES').data() * 1e3  # ms

```
        
or the pressure can be loaded directly as 
```
        pe = OMFITmdsValue(server='NSTX', treename='ACTIVESPEC', shot=shot, TDI=TS_MDS + 'FIT_PE').data()
        pe_err = OMFITmdsValue(server='NSTX', treename='ACTIVESPEC', shot=shot, TDI=TS_MDS + 'FIT_PE_ERR').data()
```

**Comment by smithsp** [comment]
There was some confusion about the use of `FIT_`, but it seems that these are the raw data points that we have been fetching in OMFITprofiles since fetching of TS was implemented 7 years ago by @orso82 https://github.com/gafusion/OMFIT-source/blame/622173f49daef1353328bc9718ba94d769be864b/modules/OMFITprofiles/SCRIPTS/NSTX/FETCH/raw_TS.py

**Comment by avdeevag** [comment]
Apparently spline fitting in NSTX MDS+ tree has a `SPLINE` in nodename

<img width="473" alt="Screen Shot 2022-09-06 at 3 00 53 PM" src="https://user-images.githubusercontent.com/80053907/188717935-09dbf381-cc6b-4bb5-a101-1555dfcd158d.png">

**Comment by smithsp** [comment]
Thanks for finding that @avdeevag .
