### ISSUE TITLE
Difference od ODS and ODC

### ISSUE THREAD

**Issue by kripnerl** [gafusion/omas#211]
Would it be possible to clarify in documentation what is deference between ODS and ODC? 

Even after studding the code it is not obvious to me what to use. 

Thank you for clarification.

**Comment by smithsp** [comment]
`ODS` is an Omas Data Structure, whose sub-elements are IMAS IDS's.
`ODC` is an Omas Data Collection, whose sub-elements are `ODS` objects.  We wanted an easy way to collect a series of `ODS` objects, each with its own identifier (via its key).

**Comment by orso82** [comment]
I am inclined to remove the `ODC` class, since in the end we have not found a good use for it (at least not in OMFIT)

**Comment by kripnerl** [comment]
Thank you for the clarification.
L
