### ISSUE TITLE
ODS Data Gets Lost During Load

### ISSUE THREAD

**Issue by bechtt** [gafusion/omas#228]
Once the machine mappings are all working, I don't have any problem dynamically viewing the systems with 
```
ods_open=ODS()
ods_open.open('d3d',pulse)
```
This is not very useful when I want to save the data to a file though, since only the data which has been loaded gets saved by
```
ods_open.save(filename)
```
It seems like the better option for this is to use
```
ods_load=ODS()
ods_load.load('d3d',pulse)
```
This takes significantly longer and prints messages for all the diagnostic systems, as I would have expected.  When I look at the data that has been loaded, however, much of it is missing
![problem](https://user-images.githubusercontent.com/1843540/217118445-f9cfb54f-e073-4705-97dc-e64acbf0523b.png)
Any idea what is going on here?  Should I be doing this differently?

**Comment by smithsp** [comment]
@bechtt Can you check your original message?  The two cases look identical to me.

**Comment by bechtt** [comment]
> @bechtt Can you check your original message? The two cases look identical to me.

Good catch!  I edited it

**Comment by smithsp** [comment]
Is it a matter of just loading the geometry (hardware) and not the data itself when using `load`?

**Comment by bechtt** [comment]
That could be what I am missing.  I'm surprised it doesn't load the geometry for the gas_injection, coils, Thomson, or many other systems either though.

Is that the primary distinction between `open` and `load`?  Is there a static option that can be passed to `open` so that it pulls everything in?  Or an option to expand all branches when `save` is called?

**Comment by orso82** [comment]
Try this:
```
ods=ODS().load("machine", "d3d", pulse=133221)
```

**Comment by bechtt** [comment]
I tried your suggestion @orso82.  It looks the same as doing the `load` in 2 lines.  The ods only has 5 systems populated

**Comment by orso82** [comment]
are those five systems fully populated?

**Comment by orso82** [comment]
```python
list_of_mappings = machine_mappings('d3d', '', None)```
should list all the things that the load function is going to load

https://github.com/gafusion/omas/blob/master/omas/omas_machine.py#L947

**Comment by bechtt** [comment]
> are those five systems fully populated?

Some of those 5 systems are only partially populated.

> ```python
> list_of_mappings = machine_mappings('d3d', '', None)
> ```
> 
> should list all the things that [he load function is going to load 

I see 217 entries in there, which seem to correspond with everything I see when I dynamically `open` the ods, but most of those do no make it into the result from `load`

**Comment by orso82** [comment]
There is a print statement saying what is getting fetched:
https://github.com/gafusion/omas/blob/master/omas/omas_machine.py#L950
do you see all systems being printed or only five?

**Comment by bechtt** [comment]
All of the systems (probably 217 but I haven't counted) get printed/fetched by `load`

**Comment by bechtt** [comment]
Addressed in #226

**Comment by smithsp** [comment]
@bechtt Was this not resolved?

**Comment by bechtt** [comment]
That's correct.  `ods.load('d3d', shot)` still does not work.  An alternative is to use `ods.open('d3d', shot)` followed by `ods.paths()`.  This was enough to do what I needed but this issue should stay open until `load` is fixed.

**Comment by smithsp** [comment]
@orso82  I think you know best what is needed here.
