### ISSUE TITLE
Error Creating/Copying ODS Entries

### ISSUE THREAD

**Issue by bechtt** [gafusion/omas#229]
This looks like a valid assignment to me and even the error message seems to suggest that it should be allowed.  So why does it raise an error at all?

```
Error in "OMFIT command box #2" at line  5
    ods_all['pf_passive.loop']=ods_pfpvv['pf_passive.loop']
LookupError: Not a valid IMAS 3.37.0 location: pf_passive.loop
                                                          ^^^^
Did you mean: code, ids_properties, loop, time
```

I don't have any problem equating the level above it
```
ods_all['pf_passive']=ods_pfpvv['pf_passive']
```
but  even after setting that, trying to reset or overwrite the next level still raises the same error

**Comment by orso82** [comment]
@bechtt this is I think the same issue as here:
https://github.com/gafusion/omas/issues/200

See there for a temporary workaround. I should really try to spend some time to address this issue...

**Comment by bechtt** [comment]
Thanks for pointing that out @orso82.  I hadn't seen that issue yet.  I will close this one
