### ISSUE TITLE
Request for version bump

### ISSUE THREAD

**Issue by LiamPattinson** [gafusion/omas#235]
I'm finishing up some work on a [PR for Pyrokinetics](https://github.com/pyro-kinetics/pyrokinetics/pull/161) which is pulling in OMAS as a dependency, but since the [latest updates to the build system](https://github.com/gafusion/omas/pull/233) aren't yet pushed to PyPI, I'm currently having to tell pip to install a specific git commit of OMAS rather than just using the version. Would it be possible to release a version 0.90.1/0.91?

**Comment by smithsp** [comment]
Done.  Thanks @orso82 for a good build/release system.

**Comment by orso82** [comment]
@smithsp my standard workflow to release a new version is:
1. edit `omas/omas/version`
2. create a commit with message `version X.Y.Z` and push (the format must be this for `make tag` to work)
3. run `make tag`
4. run `make pypi`

I suspect that you're skipping 1-3 in the process? or doing it somewhat differently?

<img width="1481" alt="image" src="https://user-images.githubusercontent.com/1537880/222827585-c9fc200f-16b4-459c-b158-67cdfb8182ca.png">

**Comment by smithsp** [comment]
I just forgot to `git push` after step 2.  In the `Makefile`, it has `git push --tags`, but that doesn't seem to pick up the branch push.

**Comment by orso82** [comment]
That explains it 👍

**Comment by orso82** [comment]
Though the commit message should have been `version 0.91.0`. I am surprised that `make tag` worked? Or maybe you tagged it manually?

<img width="280" alt="image" src="https://user-images.githubusercontent.com/1537880/222829041-e0b2f0da-a8c3-4709-ab3c-60c9071219de.png">

**Comment by smithsp** [comment]
I used `make tag`.  It seemed to work fine.

**Comment by LiamPattinson** [comment]
Thanks for this!

If there are issues with keeping things consistent with versioning, the approach I normally use is to have [setuptools-scm](https://pypi.org/project/setuptools-scm/) create a `_version.py` file dynamically from the git tags during installation, and the publishing step is handled by GitHub workflows ([here's an example of how we do it in Pyrokinetics](https://github.com/pyro-kinetics/pyrokinetics/blob/unstable/.github/workflows/python_publish.yml)). That way, we only need to create a new release on GitHub, and both the in-package version file and the PyPI upload are handled automatically. I could try implementing something similar here if you're interested.

**Comment by orso82** [comment]
Thank you for the offer @LiamPattinson but at this point the process that we have works and it takes me just a few seconds to make a new release ;) also in OMAS a lot of things are done via the Makefile, so there is some consistency with that approach. But definitely something to keep in mind for new projects!
