### ISSUE TITLE
Issues in docker and/or CI (env var USER)

### ISSUE THREAD

**Issue by hetsko** [gafusion/omas#240]
Hi.

An error is raised during import when trying to use `omas` in a **docker container** and/or **gitlab CI** pipeline, where the default user is root and traditional configurations (`.bashrc`, `.profile`) might be a bit different. The issue is the `USER` env variable, which is not set in these environments. It works with this workaround:
```bash
export USER=''
python -c 'import omas'
```

### Proposed solution

The exception points to https://github.com/gafusion/omas/blob/master/omas/omas_utils.py#L869

I feel like this check could be replaced by a simpler one using only the `UID` (which is set in docker):
```python
if os.name == 'nt' or os.environ['UID'] != os.stat(__file__).st_uid:
```
Although I have not gurantee that this is more correct and universal (will try to google), it feels like it could be.

Or just to be sure, using `get()` would also help
 ```python
... or os.environ.get('UID') != ...
```

**Comment by smithsp** [comment]
@hetsko Can you put this in a Pull Request?  Then it will be automatically tested.

**Comment by hetsko** [comment]
Sure, will try to get to it later today.
