### ISSUE TITLE
[discussion] Partial data retrieval

### ISSUE THREAD

**Issue by pfbuxton** [gafusion/omas#278]
Hello,

I'm really enjoying using OMAS and am finding it very useful + fusion seems to be converging on the IMAS standard.

However, I find it irritating that all of the data has to be retrieved from the database, even if you only want one signal. We are using the python functions for accessing the database not the direct MDSplus paths.

A typical irritation is when I want to retrieve an experimental flux loop voltage and I have to read **all** of the magnetics data which is massive!

This issue is intended for discussion and if the community feels this feature would be useful I would be happy to develop this and create a merge request.

**Comment by orso82** [comment]
@pfbuxton, I understand your concern. The granularity of data retrieval is largely dictated by the functions used for accessing that data. If multiple signals are grouped under a single function, then when you call that function, you'll get all those signals, even if you need only one of them.

To address the specific issue you mentioned about retrieving only an experimental loop voltage, consider defining a separate function solely for that purpose. This way, you can fetch just that particular signal without pulling in all the related magnetics data.

In essence, for finer control over what data you retrieve, create more specific functions for those specific sets of data.

**Comment by pfbuxton** [comment]
Thanks for the quick reply @orso82, you are very correct we can use different functions for different nodes. Perhaps I will re-organise how we do things locally.

Thanks again,
Peter
