### ISSUE TITLE
Update website to reflect latest package & IDS 

### ISSUE THREAD

**Issue by hassec** [gafusion/omas#279]
I've noticed that the website reads `Last updated on Feb 19, 2023.`. 

What do you think about generating a recent version of the documentation to update the github pages?
Among changes to the package itself, it would probably also be neat to have the 3.39.0 version of the IMAS IDS on the website.

**Comment by orso82** [comment]
done, should be updated now.

For the record, documentation can be built by `make html` (local) or `make docs` (pushing to the `gh-pages` branch and updating the website. Only admins can do this).

**Comment by hassec** [comment]
Thanks for the super speedy fix :tada:

**Comment by smithsp** [comment]
@kalling I thought we had an automated documentation builder on the jenkins server.

**Comment by orso82** [comment]
I agree @smithsp I don't remember needing to be on top of the OMAS documentation before :)

**Comment by kalling** [comment]
I know we do for omfit but would have to check if one also exists for omas

**Comment by kalling** [comment]
Since it's on ghpages and not the server, I'd guess it doesn't exist, but I'll check when I get home.  Should I make a "omas.omfit.io" page to build & host it if it doesn't exist?
