### ISSUE TITLE
the example "OMFIT gEQDSK and IMAS" from official website can't run due to the error : No module named 'xarray.plot.plot'

### ISSUE THREAD

**Issue by cameron572366** [gafusion/omas#312]
![image](https://github.com/user-attachments/assets/76b8cce7-456a-429c-aa2e-1900d20c6dcf)

**Comment by cameron572366** [comment]
and this is my "pip list", do I need to downgrade the xarray's version?
![image](https://github.com/user-attachments/assets/8c393ba7-cce0-4a02-b2a3-24aad73d047a)

**Comment by smithsp** [comment]
Thanks for reporting.  We need to restrict the version of xarray for the version of omfit_geqdsk.  There is another open issue here on omas that gives the right version of xarray.
