### ISSUE TITLE
Definition of rotation_frequency_tor_sonic in core_profile

### ISSUE THREAD

**Issue by orso82** [gafusion/omas#314]
![Screenshot2024_07_29_095421](https://github.com/user-attachments/assets/d772fd4a-d454-4614-a64d-cb3cc7146ac9)

Talking to @bclyons12 he confirmed that the (1/2pi) factor is needed, and he suggested that the GACODE website should be updated to say “poloidal flux per radian". Ping @jcandy .

In practice, I think what this means is that we should update https://github.com/gafusion/omas/blob/master/omas/omas_cocos.py with a new `transforms['TOR_dPSI'] = sigma_B0_eff * sigma_Ip_eff * sigma_Bp_eff / (2 * numpy.pi) ** exp_Bp_eff` and assign the `TOR_dPSI` to `rotation_frequency_tor_sonic` https://github.com/gafusion/omas/blob/6e14e733977b4beb79e8701b9916c2316f5b83fe/omas/omas_cocos.py#L203

@bclyons12 do you agree?

These changes should be transparent in OMFIT, since conversion from/to ODS is done using automated COCOS transform. However we should be aware that this will affect any ODS that was saved, in the sense that the convention for those old ODSs would be different than the new ones.

**Comment by jcandy** [comment]
Yes, this is described in Sec 2.2.3 of the GYRO technical manual (see image).  Where exactly does it need to be fixed in the GACODE pages?  I see one place after poking around.

![Screenshot at 2024-07-29 13-44-08](https://github.com/user-attachments/assets/6d1cdce6-ecfb-42c9-b97a-8bcc394177e9)

**Comment by bclyons12** [comment]
@jcandy It's mistaken in the last sentence of "Sonic rotation formalism" here https://gafusion.github.io/doc/rotation.html#sonic-rotation-formalism

**Comment by jcandy** [comment]
OK, that's the one I saw. LMK if you see any other issues.
