### ISSUE TITLE
Avoid MASTU related warning on import

### ISSUE THREAD

**Issue by hassec** [gafusion/omas#315]
I think it's a bit unfortunate that since `0.94` a simple
```
import omas
```

will print:
```
Could not import mast machine mappings. Check that pyuda is installed
```

That seems like a warning that shouldn't be presented to every user, but only those that actually want to use those machine mappings.

Given that `omas/__init__.py` has a `from .omas_core import *`, disentangling these imports might be tricky. But then I propose to at least remove the noisy print.

**Comment by orso82** [comment]
I have no problem with that. Please open a PR.
