### ISSUE TITLE
pFile-IMAS translation issues

### ISSUE THREAD

**Issue by bclyons12** [gafusion/omas#32]
I've been working to put the pFile into an ODS, but there are some issues getting all the information there.  We should figure out the best way to handle these, then open a JIRA issue:

1. Core profiles defines velocities, not rotations, on a rho_tor_norm grid.  Velocities are not flux quantities, so it is not clear at what major radius the velocities should be taken.  Either this should be declared (e.g., outer midplane), an R_major grid should be populated, or rotation frequency fields should be available.

2. core_profiles.profiles_1d[:].e_field asks for the flux-surface-averaged electric field, but the pFile only has the field at the outer midplane.

3. I don't see any place for the parallel stream function (Kpol in the pFile).  I could derive this from the rotations/velocities if I have corresponding R and B_tor arrays on the rho_tor_norm grid.

4. I see no place for the ExB shearing rate.  In particular, the pFile gives the Hahm-Burell expression for this.  It looks like it could be derived given info about the magnetic field and flux, but would lose accuracy since I'd have to take a flux derivative.

**Comment by bclyons12** [comment]
I now see that the there exists both core_profiles.profiles_1d[:].electrons.velocity.poloidal and core_profiles.profiles_1d[:].electrons.velocity_pol.  I have no idea what the difference.  Ditto velocity.toroidal and velocity_tor.

**Comment by orso82** [comment]
some of these quantities may be marked as obsolete.
I need to reflect this in the online OMAS documentation

**Comment by orso82** [comment]
handled with #3502
