### ISSUE TITLE
Update DD versions to 4.0.0

### ISSUE THREAD

**Issue by kripnerl** [gafusion/omas#326]
IMAS Data Dictionary currently reached versions [3.42.0](https://sharepoint.iter.org/departments/POP/CM/IMDesign/Data%20Model/sphinx/3.42/index.html#/) and [4.0.0](https://sharepoint.iter.org/departments/POP/CM/IMDesign/Data%20Model/sphinx/4.0/index.html#/). 

However, the last uploaded IMAS DD version is 3.41. 

The 3.42 update: https://github.com/gafusion/omas/pull/323

Is there any issue with the 4.0.0 version?

**Comment by orso82** [comment]
@kripnerl see https://github.com/gafusion/omas/pull/327

Let's move any further discussion about v4.0.0 there
