### ISSUE TITLE
Coordinate consistency

### ISSUE THREAD

**Issue by bclyons12** [gafusion/omas#33]
Right now, if I have an existing ODS and try to update data in it, there's no check that the coordinates I'm using for the new data are the same as what's already in the ODS. I propose the following, though I mainly want to get a discussion started.

1. Change cocos_environment to omas_environment

2. Add a new "coordinate_consistency" keyword (or similar) with the following options and behavior:
  - False:  does nothing, assumes user will ensure consistency
  - True
    - Coordinate values must be written before data can be entered
    - If a coordinate value is entered and it doesn't exist, do nothing
    - If it does exist, throw an exception if the grid is not the same as already in place
    - If data is entered, ensure the dimensionality conforms with the coordinates
  - 'new'
    - New coordinates can be declared, overwriting old ones
    - If a new coordinate is declared, existing data in tree is automatically interpolated
    - All new data entered is checked for dimensionality conformity with the new coordinate
  - 'old'
    - New coordinates can be declared but do not overwrite old ones
    - All new data entered gets interpolated onto the old coordinates

**Comment by smithsp** [comment]
Sounds like a good idea to me.
