### ISSUE TITLE
Function to find time_slice at a given time

### ISSUE THREAD

**Issue by bclyons12** [gafusion/omas#42]
Typically I might know a time for which I want data, but I won't know what `time_slice` that occurs at within an ODS. There's a `slice_at_time` function, but that appears to literally slice the ODS at that time (at labels it `time_slice`=0). Could you please write a function that would just return the integer `time_slice` that a given time corresponds to?

There's also a complication of where the time get set. For example, within OMFIT's `OMFITgeqdsk.to_omas`, the time from a gEQDSK gets set to `ods['equilibrium.time_slice'][time_index]['time']`, but does not get put in the `ods['equilibrium.time']` array. It looks like `slice_at_time` is only looking for the former.

**Comment by orso82** [comment]
@bclyons12 you should be able to do that easily by doing `ods.time().index(1000.)`, for example.

**Comment by bclyons12** [comment]
@orso82 That works with the exception that `time()` returns an ndarray, not a list, you you  need to do' `where(ods.time()==4.2)[0][0]` or `ods.time().tolist().index(4.2)`.
