### ISSUE TITLE
equilibrium.time_slice[:].profiles_1d.psi

### ISSUE THREAD

**Issue by bclyons12** [gafusion/omas#45]
One of the fundamental coordinates for the equilibrium IDS is equilibrium.time_slice[:].profiles_1d.psi.  This is a strange choice, however, as the limits of the psi grid can change as an equilibrium evolves.  This is causing a problem in which I try to write a new gEQDSK to an existing ODS, but SIBRY has decreased.  Thus, something like rho_tor_norm, which should always go from 0 to 1 but uses psi as a coordinate, gets truncated when interpolating onto the old psi grid.  A few options for how to fix this:

1) A coordinate shouldn't change in time, so psi is a terrible choice.  We could open a JIRA issue and request that the equilibrium IDS use something fixed and/or normalized.  psi_norm would make sense, though it doesn't exist in that IDS right.  rho_tor_norm does, but is not a coordinate typically used in MHD equilibrium calculations.

2) Unlike core_profiles, in which different quantities could come from different codes and diagnostics, an equilibrium should probably be entirely self-consistent.  If something is writing to that IDS, perhaps we should assume that everything is getting updated self-consistently.  In OMFIT, this would take the form of wiping the equilibrium before writing a new one.  This would be good coding practice for users, but probably wouldn't need to be done at the framework level.

**Comment by orso82** [comment]
@bclyons12 I can only wholeheartedly agree with you.
Let me open a IMAS jira issue and let's see what happens!

**Comment by jsferreira** [comment]
I don't quite get it. Each time_slice is a equilibrium reconstruction/solution for a given time. I don't see the need to map/interpolate profiles. The fields should be filled with what comes from the equilibrium code. Even a normalised psi grid can change in time. Only the boundaries (0.0,1.0) don't change. The psi_norm is a derived quantity, so I am not sure if it is really necessary to be added do the data structure.

**Comment by bclyons12** [comment]
@jsferreira I agree that `psi_norm` can change in time, but the important part is that the domain does not. Thus, if new data is input, it defines over that entire domain and never gets truncated. The fact that the domain of `psi` changes over time make is a terrible choice for a coordinate.

I agree with you that an equilibrium IDS should probably be entirely consistent internally. I still could imagine situations in which the data could be given at different resolutions for different quantities, making the capability to interpolate internally useful.
