### ISSUE TITLE
profiles2d dimension order

### ISSUE THREAD

**Issue by kripnerl** [gafusion/omas#53]
All over the OMAS/OMFIT code, there is consistently assumed that the 2D equilibrium variables has shape `[equilibrium.time_slice[:].profiles_2d[:].grid.dim2, equilibrium.time_slice[:].profiles_2d[:].grid.dim1]`. However, according to the presented IMAS data-structure (https://gafusion.github.io/omas/schema/schema_equilibrium.html), 2d variables should have shape `[equilibrium.time_slice[:].profiles_2d[:].grid.dim1, equilibrium.time_slice[:].profiles_2d[:].grid.dim2]`, i.e. to be transposed with respect to the implemented convention. 

My colleague used OMAS to store data to IMAS on Gateway to run the ASCOT code (I think it required IMAS v 3.17) and he obtained correct results only if he used `[dim1, dim2]` shape of the `psi` matrix. 

For example the order `[dim2, dim1]` is required here: 
https://github.com/gafusion/omas/blob/c827e373770f381bf407588f63f44fad5802d2e9/omas/omas_plot.py#L419-L434

https://github.com/gafusion/omas/blob/c827e373770f381bf407588f63f44fad5802d2e9/omas/omas_plot.py#L63-L68

**Comment by orso82** [comment]
@kripnerl thank you for pointing that out 👍 

I have given you developers permission to the repository. Would you be able to push the fix for OMAS yourself on a separate branch. I'll take care of fixing the OMFIT classes.

**Comment by kripnerl** [comment]
I am looking forward to it.

**Comment by kripnerl** [comment]
It seems to me, that only place where it is needed to change it in OMAS is here b675e2527b93863b0287548bc7a6decfe7f4fd80; however, I suppose that all stored testing data has an opposite order as well as all routines from_omas and to_omas in OMFIT, I will do the same branch there and check consistency.

**Comment by kripnerl** [comment]
The change in OMFIT is here: https://github.com/gafusion/OMFIT-source/commit/adc71d644d2b4286e2901afb64237dffd5a53425
I haven't found any other place where the transposition would be needed.

**Comment by orso82** [comment]
Fixed with b675e2527b93863b0287548bc7a6decfe7f4fd80
