### ISSUE TITLE
ODS needs deepcopy ability

### ISSUE THREAD

**Issue by smithsp** [gafusion/omas#55]
As mentioned in https://github.com/gafusion/OMFIT-source/commit/f4d328b9379c27eeb7c346108b83c858347bebf9#commitcomment-32071184, the `ODS` class needs the ability to turn off checks during `deepcopy`.

**Comment by orso82** [comment]
@smithsp i checked and the ODS consistency checks are not active when doing a deepcopy of an ODS, so the slow issue seen on https://github.com/gafusion/OMFIT-source/commit/f4d328b9379c27eeb7c346108b83c858347bebf9 may be indeed only due to the amount of data or how nested the data is.
