### ISSUE TITLE
List IMAS issues to be discussed at upcoming IMAS code-camp

### ISSUE THREAD

**Issue by orso82** [gafusion/omas#58]
@gafusion/omas_developers I will be attending the IMAS code camp in early April. Please let me know here if you have issues/complaints with the IMAS data structure that you would like me to bring up when I am there.

* use of `equilibrium.time_slice[:].profiles_1d.psi` as coordinate is a terrible idea #45
* summary IDS is a catch-all
* rotation (simulations use rotation frequencies, experiments use (midplane) velocities):
  - core_profiles.profiles_1d[:].omega0 (http://gafusion.github.io/doc/rotation.html)
  - core_profiles.profiles_1d[:].electrons.rotation.perpendicular
  - core_profiles.profiles_1d[:].electrons.rotation.diamagnetic
  - core_profiles.profiles_1d[:].electrons.parallel_stream_function
  - core_profiles.profiles_1d[:].electrons.velocity.poloidal
  - core_profiles.profiles_1d[:].electrons.velocity.radial
  - core_profiles.profiles_1d[:].electrons.velocity.toroidal
  - core_profiles.profiles_1d[:].ion[:].rotation.perpendicular
  - core_profiles.profiles_1d[:].ion[:].rotation.diamagnetic
  - core_profiles.profiles_1d[:].ion[:].rotation.parallel_stream_function
  - core_profiles.profiles_1d[:].ion[:].velocity.poloidal
  - core_profiles.profiles_1d[:].ion[:].velocity.radial
  - core_profiles.profiles_1d[:].ion[:].velocity.toroidal

* geometry
  - equilibrium.time_slice[:].profiles_1d.centroid
  - equilibrium.time_slice[:].profiles_1d.centroid.r_max
  - equilibrium.time_slice[:].profiles_1d.centroid.r_min
  - equilibrium.time_slice[:].profiles_1d.centroid.r
  - equilibrium.time_slice[:].profiles_1d.centroid.z

* per-quantity cocos transform rule https://github.com/gafusion/omas/blob/master/omas/omas_cocos.py should be part of IMAS data structure

* obsolescent fields should have a pointer to what they got renamed to (if it's only  a rename: eg. `b_tor`-->`b_field_tor`)
* equilibrium_2d R/Z coordinates are flipped for some cases: eg. pulse 130501

* Are machine parameters (such as `pf_active`) in COCOS11

**Comment by jsferreira** [comment]
Concerning the missing fields, I fully agree. We need a place for omega0 and if velocity.* is obsolescent now, where are we going to store the components of velocity/rotation/momentum ?

We have to be careful with the centroid data structure. Is the real centroid or is it taken at the midplane crossing the magnetic axis? Mind that r_inboard and r_outboard are taken at the later one. It is true that at the mid plane crossing the mag. axis, r,z,rmax,rmin can be derived in principle from r_inboard/r_outboard.

**Comment by orso82** [comment]
@jsferreira in this case we'd be seeking the true centroid
