### ISSUE TITLE
Failing import of OMAS

### ISSUE THREAD

**Issue by kripnerl** [gafusion/omas#62]
I am running pytests in `gitlab` CI and it seems that the enviroment has not `USER` enviroment and as a consequence the test fails.
Not sure whether is this bug or not. 

```python
_____________________ ERROR collecting tests/omas_test.py ______________________
tests/omas_test.py:4: in <module>
    import omas
/opt/conda/envs/pleque/lib/python3.6/site-packages/omas/__init__.py:1: in <module>
    from .omas_core import *
/opt/conda/envs/pleque/lib/python3.6/site-packages/omas/omas_core.py:1219: in <module>
    from .omas_imas import *
/opt/conda/envs/pleque/lib/python3.6/site-packages/omas/omas_imas.py:364: in <module>
    def load_omas_imas(user=os.environ['USER'], machine=None, pulse=None, run=0, paths=None,
/opt/conda/envs/pleque/lib/python3.6/os.py:669: in __getitem__
    raise KeyError(key) from None
E   KeyError: 'USER'
```

**Comment by orso82** [comment]
Can try to substitute `os.environ['USER']` for `os.environ.get('USER','dummy_user')`, however I suspect that maybe other environmental variables may not be available then. How about `os.environ['HOME']` ?

If it works could you please open a PR ?

**Comment by kripnerl** [comment]
Thx. Yop. This may help. I will try to push it tomorrow. 

Btw. see you on ITER :-).
