### ISSUE TITLE
Installation of OMAS on NERSC

### ISSUE THREAD

**Issue by sfrnk** [gafusion/omas#68]
Has anybody tried installing OMAS on NERSC? Specifically, I am trying to install it on Cori and running into the following error when I try to run the "pip install ..." command when installing from a pull of the git repo. The error is the following

> ERROR: Invalid requirement: 'build_documentation]'

Any help would be appreciated.

**Comment by orso82** [comment]
@sfrnk there was an extra space in the documentation for installing OMAS from sources:
```
sudo pip install --upgrade -e .[build_structures, build_documentation]
```
should instead be:
```
sudo pip install --upgrade -e .[build_structures,build_documentation]
```

I have updated the installation documentation page accordingly:
https://gafusion.github.io/omas/install.html

Can you please try again with the new syntax, and close this issue if it works for you.

**Comment by sfrnk** [comment]
Alright that about fixed it. I had to add an additional --user flag to get this to work on NERSC with the way permissions are set there.
