### ISSUE TITLE
ModuleNotFoundError in omfit_eqsk routine

### ISSUE THREAD

**Issue by sfrnk** [gafusion/omas#69]
Hi, there is what looks to be a Python 2 compatibility issue with the omfit_eqdsk routine that leads to the following error being thrown:

> File "/global/homes/s/sfrnk/IPS_work/OMFIT/OMFIT-source/omfit/classes/omfit_eqdsk.py", line 11, in <module>
>     except ModuleNotFoundError:  # catch error in Python3.x
> NameError: name 'ModuleNotFoundError' is not defined

I have commented out the incompatible code for now in my build, but would a more robust fix be possible?

**Comment by smithsp** [comment]
@sfrnk What was the resolution here?

**Comment by smithsp** [comment]
I am going to transfer this issue to the OMFIT repo (and give @sfrnk access there).
